language: rust
rust:
  - nightly
cache: cargo

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - binutils-arm-none-eabi

env:
  - TARGET=thumbv6m-none-eabi

before_script:
  - rustup component add --toolchain nightly rustfmt-preview
  - which rustfmt || cargo install --force rustfmt-nightly
  - which xargo || cargo install xargo
  - rustup component list | grep 'rust-src.*installed' || rustup component add rust-src
  - set -e

script:
  - cargo clean
  - xargo check --target $TARGET
  - xargo build --target $TARGET --examples --all-features
  - cargo +nightly fmt --all -- --write-mode=diff

after_script:
  - set +e
